config/routes.rb
Rails.application.routes.draw do
  root to: 'customer/homes#top'
  get 'admin' => 'admin/homes#top'
  get 'about' => 'customer/homes#about'

  devise_for :admins, controllers: {
    sessions:      'admin_devises/sessions',
    passwords:     'admin_devises/passwords',
    registrations: 'admin_devises/registrations'
  }

   devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

  namespace :admin do
    
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update] do
      member do
        get 'customer_orders'
      end
    end
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :customer do
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'quit'
        patch 'withdraw'
      end
    end
    resources :items, only: [:index, :show]
    resources :orders, only: [:index, :show, :new, :create] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :phone_number, format: { with: /\A\d{10,11}\z/}

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy


  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
	has_many :order_items, dependent: :destroy
  validates :adresse_postal_code, format: { with: /\A\d{7}\z/ }
  validates :adresse_street_adress, presence: true
  validates :adresse_name, presence: true

  def full_address
    return "〒" + self.addrese_postal_code + " " + self.adresse_street_adress
  end

  def total_payment
    total_price = 0
    self.order_items.each do |item|
      total_price += item.purchase_price * item.quantity
    end
    return self.adresse_fee + total_price
  end

  def  total_count
    total_count = 0
    self.order_items.each do |item|
      total_count += item.quantity
    end
    return total_count
  end

  enum method_of_payment: {クレジットカード: 0, 銀行振込: 1}

  enum status: {入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    flash[:success] = "会員情報を更新しました"
    redirect_to admin_customer_path(@customer)
  end

  def customer_orders
    @customer = Customer.find(params[:id])
  end

  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :addrees, :email, :is_deleted)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def updatepara
    @order = Order.find(params[:id])
    @order.update(order_params)
    if params[:order][:order_status] = "1"
      @order.order_details.each do |order_detail|
        order_detail.update(production_status: 1)
      end
    end
    flash[:success] = "注文ステータスを更新しました"
    redirect_to admin_order_path(@order)
  end

  private
  def order_params
    params.require(:order).permit(:order_status)
  end
end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController
    def index
        @address = Address.new
        @addresses = Address.all
    end

    def create
        @address = Address.new(address_params)
        @address.end_user_id = current_end_user.id
        @address.save
        flash[:success] = "配送先を登録しました"
        redirect_to addresses_path
    end

    def edit
        @address = Address.find(params[:id])
    end

    def update
        @address = Address.find(params[:id])
        @address.update(address_params)
        flash[:success] = "配送先を更新しました"
        redirect_to addresses_path
    end

    def destroy
        @address = Address.find(params[:id])
        @address.destroy
        flash[:success] = "配送先を削除しました"
        redirect_to addresses_path
    end

    private
    def address_params
        params.require(:address).permit(:name, :address, :postal_code)
    end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  def index
    @cart_items = CartItem.all
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    @update_cart_item = CartItem.find_by(item_id: @cart_item.item_id)

    if @update_cart_item.present?
      @cart_item.amount += @update_cart_item.amount
      @update_cart_item.destroy
    end

    if @cart_item.save
      redirect_to cart_items_path
    else
      @item = Item.find(params[:cart_item][:item_id])
      @cart_item = CartItem.new
      render 'customer/items/show'
    end
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(amount: (params[:cart_item][:amount]))
    redirect_to cart_items_path
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    flash[:success] = "商品を削除しました"
    redirect_to cart_items_path
  end

  def destroy_all
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    flash[:success] = "カート内のすべての商品を削除しました"
    redirect_to cart_items_path
  end
  private
  def cart_item_params
    params.require(:cart_item).permit(:item_id, :amount)
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def withdraw
    @customer = Customer.find(params[:id])
    @customer.update(is_vaild: true)
    reset_session
    redirect_to root_path
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customers_customer_path(@customer.id)
    else
      render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :email, :postal_code, :addrees, :phone_number)
  end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  def top
    @items = Item.page(params[:page]).reverse_order.per(4)
  end

  def about
  end

end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!
  before_action :check_cart_item, except: :complete

  def new
    @order = Order.new
    @addresses = Addresse.where(customer_id: current_customer.id)
  end

  def confirm
    @cart_items = current_customer.cart_items
    @order = Order.new(
    customer: current_customer,
    payment_method: params[:order][:payment_method]
    )

    if params[:order][:address_option] == "0"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name + current_customer.first_name

    elsif params[:order][:address_option] == "1"
      @ship = Address.find(params[:order][:address_id])
      @order.postal_code = @ship.postal_code
      @order.address = @ship.address
      @order.name = @ship.name

    elsif params[:order][:address_option] = "2"
      @order.postal_code = params[:order][:postal_code]
      @order.address = params[:order][:address]
      @order.name = params[:order][:name]

    end
  end

  def create
    @order = current_customer.orders.new(order_params)
    @order.save
    @cart_items = current_customer.cart_items
    if @order.total_payment != total_payment(@cart_items)
      current_customer.update(point: 0)
    end

    @cart_items.destroy_all
    redirect_to complete_orders_path
  end

  def index
    @orders = current_customer.orders
  end

  def show
    @order = Order.find(params[:id])
  end

  def complete
  end

  private
  def order_params
    params.require(:order).permit(:postal_code, :address, :name, :payment_method, :total_price)
  end

  def address_params
    params.require(:order).permit(:postal_code, :address, :name)
  end

  def check_cart_item
   unless current_customer.cart_items.present?
     redirect_to cart_items_path
   end
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    customer_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  def tax_price(price)
    (price*1.1).floor
  end

  # 小計の計算
  def sub_price(sub)
    (tax_price(sub.item.price) * sub.amount)
  end

  # 合計金額の計算
  def total_price(totals)
    price = 0
    totals.each do |total|
      price += sub_price(total)
    end
    return price
  end

  # 請求合計金額の計算（注文履歴詳細画面）
  def billing_admin(order)
    total_price(order.order_details) + order.shoping_cost
  end
end

app/views/customer/orders/comfirm.html.erb
<div class="container">
  <div class="row mb-3">
    <div class="col-md-8">
      <h3>注文情報確認</h3>
    </div>

  </div>
  <div class="row">
    <div class="col-md-8">
      <table class= "table table-bordered">
        <tr class= "thead-light">
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
        </tr>
        <% @cart_items.each do |cart_item| %>
        <tr>
          <td>
            <div class="form-inline">
              <%= attachment_image_tag cart_item.item, :image, fallback: "no-image.png", size: "50x50" %>
              <p class= "ml-3 mb-0"><%= cart_item.item.name %></p>
            </div>
          </td>
          <td>
            <p class= "mt-2"><%= tax_price(cart_item.item.price).to_s(:delimited) %></p>
          </td>
          <td>
            <div class="form-inline">
              <p class= "mb-0 mt-2"><%= cart_item.amount %></p>
            </div>
          </td>
          <td>
            <p class= "mt-2"><%= sub_price(cart_item).to_s(:delimited) %></p>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
    <div class="col-md-4">
      <table class= "table table-bordered">
        <tr>
          <th class= "table-active">送料</th>
          <td>¥<%= @order.postage %></td>
        </tr>
        <tr>
          <th class= "table-active">商品合計</th>
          <td>¥<%= total_price(@cart_items).to_s(:delimited) %></td>
        </tr>
        <tr>
          <th class= "table-active">合計金額</th>
            <td>¥<%= billing(@order).to_s(:delimited) %></td>
        </tr>
        <tr>
          <th class= "table-active">ご請求金額</th>
          <td>¥<%= (@order.total_price + @order.postage).to_s(:delimited)  %></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md">
      <table class= "table table-bordered">
        <tr>
          <th class= "table-active">支払い方法</th>
          <td><%= @order.payment_method %></td>
        </tr>
         <tr>
          <th class= "table-active">お届け先</th>
          <td><%= "〒#{@order.postal_code} #{@order.address} #{@order.name}" %></td>
        </tr>
      </table>
    </div>
  </div>

  <div class="text-center">
   <%= form_with model: @order, url: orders_path, method: :post, local: true do |f| %>
     <%= f.hidden_field :postal_code %>
     <%= f.hidden_field :address %>
     <%= f.hidden_field :name %>
     <%= f.hidden_field :payment_method %>
     <%= f.hidden_field :total_price %>
     <%= f.submit "購入を確定する", data: {confirm: "注文を確定しますか？"}, class: "btn btn-primary" %>
   <% end %>
  </div>
</div>

app/views/customer/orders/complete.html.erb
<div class= "container">
    <div class= "row">
        <div class= "col-md">
          <h2 class= "text-center mt-5">ご注文ありがとうございました！</h2>
        </div>
    </div>
</div>

app/views/customer/orders/confirm.html.erb
<div class="container">
  <div class="row mb-3">
    <div class="col-md-8">
      <h3>注文情報確認</h3>
    </div>

  </div>
  <div class="row">
    <div class="col-md-8">
      <table class= "table table-bordered">
        <tr class= "thead-light">
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
        </tr>
        <% @cart_items.each do |cart_item| %>
        <tr>
          <td>
            <div class="form-inline">
              <%= attachment_image_tag cart_item.item, :image, fallback: "no-image.png", size: "50x50" %>
              <p class= "ml-3 mb-0"><%= cart_item.item.name %></p>
            </div>
          </td>
          <td>
            <p class= "mt-2"><%= tax_price(cart_item.item.price).to_s(:delimited) %></p>
          </td>
          <td>
            <div class="form-inline">
              <p class= "mb-0 mt-2"><%= cart_item.amount %></p>
            </div>
          </td>
          <td>
            <p class= "mt-2"><%= sub_price(cart_item).to_s(:delimited) %></p>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
    <div class="col-md-4">
      <table class= "table table-bordered">
        <tr>
          <th class= "table-active">送料</th>
          <td>¥<%= @order.shoping_cost %></td>
        </tr>
        <tr>
          <th class= "table-active">商品合計</th>
          <td>¥<%= total_price(@cart_items).to_s(:delimited) %></td>
        </tr>
        <tr>
          <th class= "table-active">合計金額</th>
            <td>¥<%= billing(@order).to_s(:delimited) %></td>
        </tr>
        <tr>
          <th class= "table-active">ご請求金額</th>
          <td>¥<%= (@order.total_price + @order.shoping_cost).to_s(:delimited)  %></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md">
      <table class= "table table-bordered">
        <tr>
          <th class= "table-active">支払い方法</th>
          <td><%= @order.payment_method %></td>
        </tr>
         <tr>
          <th class= "table-active">お届け先</th>
          <td><%= "〒#{@order.postal_code} #{@order.address} #{@order.name}" %></td>
        </tr>
      </table>
    </div>
  </div>

  <div class="text-center">
   <%= form_with model: @order, url: orders_path, method: :post, local: true do |f| %>
     <%= f.hidden_field :postal_code %>
     <%= f.hidden_field :address %>
     <%= f.hidden_field :name %>
     <%= f.hidden_field :payment_method %>
     <%= f.hidden_field :total_price %>
     <%= f.submit "購入を確定する", data: {confirm: "注文を確定しますか？"}, class: "btn btn-primary" %>
   <% end %>
  </div>
</div>

app/views/customer/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md">
      <h3 class= "mb-3">注文履歴一覧</h3>
      <table class= "table table-bordered">
        <tr class= "thead-light ">
          <th>注文日</th>
          <th>配送先</th>
          <th>注文商品</th>
          <th>支払い金額</th>
          <th>ステータス</th>
          <th>注文詳細</th>
        </tr>
        <% @orders.each do |order| %>
        <tr>
          <td><%= l order.created_at %></td>
          <td><%= order.address %></td>
          <td>
            <% order.order_details.each do |order_detail| %>
              <%= order_detail.item.name %>
            <% end %>
          </td>
          <td><%= order.total_price.to_s(:delimited) %></td>
          <td><%= order.order_status %></td>
          <td>
            <%= link_to "表示する", order_path(order), class: "btn btn-primary btn-sm" %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/customer/orders/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md">
      <h3>注文情報入力</h3>
      <%= form_with model: @order, url: confirm_orders_path, method: :post, local: true do |f| %>
        <h4 class= "mt-4">支払い方法</h4>
        <div class="form-group">
          <%= f.radio_button :payment_method, "クレジットカード", checked: true %>
          <%= f.label :payment_method_クレジットカード, "クレジットカード" %>
          <%= f.radio_button :payment_method, "銀行振込", checked: false %>
          <%= f.label :payment_method_銀行振込, "銀行振込" %>
        </div>
        <h4>お届け先</h4>
        <div class="form-group">
          <%= f.radio_button :address_option, 0, checked: true %>
          <%= f.label :address_option_0, "ご自身の住所" %><br>
          <%= "〒#{current_customer.postal_code} #{current_customer.address}" %><br>
          <%= "#{current_customer.last_name}#{current_customer.first_name}" %>
        </div>
        <div class="form-group">
          <%= f.radio_button :address_option, 1, checked: false %>
          <%= f.label :address_option_1, "登録済み住所から選択" %><br>
          <%= f.collection_select(:address_id, @addresses, :id, :order_address, {prompt: "住所を選択してください"}, {class: "form-control w-75"}) %>
        </div>
        <div class="form-group">
          <%= f.radio_button :address_option, 2, checked: false %>
          <%= f.label :address_option_2, "新しいお届け先" %><br>
          <div class="form-inline">
            <%= f.label :"郵便番号", class: "mr-3" %>
            <%= f.text_field :postal_code, class: "form-control w-25 mb-2"%>
          </div>
          <div class="form-inline">
            <%= f.label :"住所", class: "mr-5" %>
            <%= f.text_field :address, class: "form-control w-50 mb-2"%>
          </div>
          <div class="form-inline">
            <%= f.label :"宛名", class: "mr-5" %>
            <%= f.text_field :name, class: "form-control w-25"%>
          </div>
        </div>

        <div class="text-center">
          <%= f.submit "確認画面に進む", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/customer/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md">
      <h3 class= "mb-3">注文履歴詳細</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <h4>注文情報</h4>
      <table class= "table table-bordered">
        <tr>
          <th class= "table-active">注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th class="table-active">配送先</th>
          <td><%= @order.address %></td>
        </tr>
        <tr>
          <th class= "table-active">支払い方法</th>
          <td><%= @order.payment_method %></td>
        </tr>
        <tr>
          <th class= "table-active">ステータス</th>
          <td><%= @order.order_status %></td>
        </tr>
      </table>
    </div>
    <div class="col-md-4">
      <h4>請求情報</h4>
      <table class= "table table-bordered">
        <tr>
          <th class= "table-active">商品合計</th>
          <td><%= @order.total_price.to_s(:delimited) %></td>
        </tr>
        <tr>
          <th class= "table-active">配送料</th>
          <td><%= @order.shoping_cost %></td>
        </tr>
        <tr>
          <th class= "table-active">ご請求額</th>
          <td><%= billing_customer(@order).to_s(:delimited) %></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md">
      <h4>注文内容</h4>
      <table class= "table table-bordered">
        <tr class= "thead-light">
          <th>商品</th>
          <th>単価(税込)</th>
          <th>個数</th>
          <th>小計</th>
        </tr>
        <% @order.order_details.each do |order_detail| %>
        <tr>
          <td><%= order_detail.item.name %></td>
          <td><%= order_detail.item.price.to_s(:delimited) %></td>
          <td><%= order_detail.amount %></td>
          <td><%= sub_price(order_detail).to_s(:delimited) %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>