config/routes.rb
Rails.application.routes.draw do
  root to: 'customer/homes#top'
  get 'admin' => 'admin/homes#top'
  get 'about' => 'customer/homes#about'

  devise_for :admins, controllers: {
    sessions:      'admin_devises/sessions',
    passwords:     'admin_devises/passwords',
    registrations: 'admin_devises/registrations'
  }

   devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

  namespace :admin do
    
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update] do
      member do
        get 'customer_orders'
      end
    end
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :customer do
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'quit'
        patch 'withdraw'
      end
    end
    resources :items, only: [:index, :show]
    resources :orders, only: [:index, :show, :new, :create] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :phone_number, format: { with: /\A\d{10,11}\z/}

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy


  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    flash[:success] = "会員情報を更新しました"
    redirect_to admin_customer_path(@customer)
  end

  def customer_orders
    @customer = Customer.find(params[:id])
  end

  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :addrees, :email, :is_deleted)
  end

end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController
    def index
        @address = Address.new
        @addresses = Address.all
    end

    def create
        @address = Address.new(address_params)
        @address.end_user_id = current_end_user.id
        @address.save
        flash[:success] = "配送先を登録しました"
        redirect_to addresses_path
    end

    def edit
        @address = Address.find(params[:id])
    end

    def update
        @address = Address.find(params[:id])
        @address.update(address_params)
        flash[:success] = "配送先を更新しました"
        redirect_to addresses_path
    end

    def destroy
        @address = Address.find(params[:id])
        @address.destroy
        flash[:success] = "配送先を削除しました"
        redirect_to addresses_path
    end

    private
    def address_params
        params.require(:address).permit(:name, :address, :postal_code)
    end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  def index
    @cart_items = CartItem.all
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    @update_cart_item = CartItem.find_by(item_id: @cart_item.item_id)

    if @update_cart_item.present?
      @cart_item.amount += @update_cart_item.amount
      @update_cart_item.destroy
    end

    if @cart_item.save
      redirect_to cart_items_path
    else
      @item = Item.find(params[:cart_item][:item_id])
      @cart_item = CartItem.new
      render 'customer/items/show'
    end
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(amount: (params[:cart_item][:amount]))
    redirect_to cart_items_path
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    flash[:success] = "商品を削除しました"
    redirect_to cart_items_path
  end

  def destroy_all
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    flash[:success] = "カート内のすべての商品を削除しました"
    redirect_to cart_items_path
  end
  private
  def cart_item_params
    params.require(:cart_item).permit(:item_id, :amount)
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def withdraw
    @customer = Customer.find(params[:id])
    @customer.update(is_vaild: true)
    reset_session
    redirect_to root_path
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customers_customer_path(@customer.id)
    else
      render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :email, :postal_code, :addrees, :phone_number)
  end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  def top
    @items = Item.page(params[:page]).reverse_order.per(4)
  end

  def about
  end

end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!
  before_action :check_cart_item, except: :complete

  def new
    @order = Order.new
    @addresses = Addresse.where(customer_id: current_customer.id)
  end

  def confirm
    @cart_items = current_customer.cart_items
    @order = Order.new(
    customer: current_customer,
    payment_method: params[:order][:payment_method]
    )

    if params[:order][:address_option] == "0"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name + current_customer.first_name

    elsif params[:order][:address_option] == "1"
      @ship = Address.find(params[:order][:address_id])
      @order.postal_code = @ship.postal_code
      @order.address = @ship.address
      @order.name = @ship.name

    elsif params[:order][:address_option] = "2"
      @order.postal_code = params[:order][:postal_code]
      @order.address = params[:order][:address]
      @order.name = params[:order][:name]

    end
  end

  def create
    @order = current_customer.orders.new(order_params)
    @order.save
    @cart_items = current_customer.cart_items
    if @order.total_payment != total_payment(@cart_items)
      current_customer.update(point: 0)
    end

    @cart_items.destroy_all
    redirect_to complete_orders_path
  end

  def index
    @orders = current_customer.orders
  end

  def show
    @order = Order.find(params[:id])
  end

  def complete
  end

  private
  def order_params
    params.require(:order).permit(:postal_code, :address, :name, :payment_method, :total_price)
  end

  def address_params
    params.require(:order).permit(:postal_code, :address, :name)
  end

  def check_cart_item
   unless current_customer.cart_items.present?
     redirect_to cart_items_path
   end
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    customer_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <h3 class= "mb-5"><%= "#{@customer.last_name}#{@customer.first_name}さんの会員情報編集" %></h3>
      <%= form_for @customer, url: admin_customer_path, method: :patch do |f| %>
        <table class= "table table-borderless">
          <tr>
            <th>会員id</th>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th>氏名</th>
            <td>
              <div class="form-inline">
                <%= f.text_field :last_name, class: "form-control" %>
                <%= f.text_field :first_name, class: "form-control" %>
              </div>
            </td>
          </tr>
          <tr>
            <th>フリガナ</th>
            <td>
              <div class="form-inline">
                <%= f.text_field :last_name_kana, class: "form-control" %>
                <%= f.text_field :first_name_kana, class: "form-control" %>
              </div>
            </td>
          </tr>
          <tr>
            <th>郵便番号</th>
            <td><%= f.text_field :postal_code, class: "form-control" %></td>
          </tr>
          <tr>
            <th>住所</th>
            <td><%= f.text_field :address, class: "form-control" %></td>
          </tr>
          <tr>
            <th>電話番号</th>
            <td><%= f.text_field :phone_number, class: "form-control" %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= f.text_field :email, class: "form-control" %></td>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <td>
              <%= f.radio_button :is_deleted, false %>
              <%= f.label :is_deleted, "有効", {value: :false, style: "display: inline-block;"} %>
              <%= f.radio_button :is_deleted, true %>
              <%= f.label :is_active, "退会", {value: :true, style: "display: inline-block;"} %>
            </td>
          </tr>
          <tr>
            <th></th>
            <td><%= f.submit :"変更を保存", class: "btn btn-success" %></td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md">
      <h3>会員一覧</h3>
      <table class= "table">
        <tr>
          <th>会員id</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>会員ステータス</th>
        </tr>
        <% @customers.each do |customer| %>
        <tr>
            <td><%= customer.id %></td>
            <td>
              <%= link_to admin_customer_path(customer), class: "text-primary" do %>
                <%= customer.last_name %><%= customer.first_name %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_deleted == true %>
                <p>退会</p>
              <% elsif customer.is_deleted == false %>
                <p class="text-success">有効</p>
              <% end %>
            </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3 class= "mb-5"><%= "#{@customer.last_name}#{@customer.first_name}さんの会員詳細" %></h3>
      <table class= "table">
        <tr>
          <th>会員id</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= "#{@customer.last_name}#{@customer.first_name}" %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= "#{@customer.last_name_kana}#{@customer.first_name_kana}" %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @customer.phone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td>
            <% if @customer.is_deleted == true %>
            <p>退会</p>
            <% elsif @customer.is_deleted == false %>
            <p class="text-success">有効</p>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md text-center">
      <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %>
      <%= link_to '注文履歴一覧を見る', admin_orders_path(id: @customer.id), class: "btn btn-primary" %>
    </div>
  </div>
</div>