config/routes.rb
Rails.application.routes.draw do
  root to: 'customer/homes#top'
  get 'admin' => 'admin/homes#top'
  get 'about' => 'customer/homes#about'

  devise_for :admins, controllers: {
    sessions:      'admin_devises/sessions',
    passwords:     'admin_devises/passwords',
    registrations: 'admin_devises/registrations'
  }

   devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

  namespace :admin do
    
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update] do
      member do
        get 'customer_orders'
      end
    end
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :customer do
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'quit'
        patch 'withdraw'
      end
    end
    resources :items, only: [:index, :show]
    resources :orders, only: [:index, :show, :new, :create] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
	has_many :order_items, dependent: :destroy
  validates :adresse_postal_code, format: { with: /\A\d{7}\z/ }
  validates :adresse_street_adress, presence: true
  validates :adresse_name, presence: true

  def full_address
    return "〒" + self.addrese_postal_code + " " + self.adresse_street_adress
  end

  def total_payment
    total_price = 0
    self.order_items.each do |item|
      total_price += item.purchase_price * item.quantity
    end
    return self.adresse_fee + total_price
  end

  def  total_count
    total_count = 0
    self.order_items.each do |item|
      total_count += item.quantity
    end
    return total_count
  end

  enum method_of_payment: {クレジットカード: 0, 銀行振込: 1}

  enum status: {入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def updatepara
    @order = Order.find(params[:id])
    @order.update(order_params)
    if params[:order][:order_status] = "1"
      @order.order_details.each do |order_detail|
        order_detail.update(production_status: 1)
      end
    end
    flash[:success] = "注文ステータスを更新しました"
    redirect_to admin_order_path(@order)
  end

  private
  def order_params
    params.require(:order).permit(:order_status)
  end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!
  before_action :check_cart_item, except: :complete

  def new
    @order = Order.new
    @addresses = Addresse.where(customer_id: current_customer.id)
  end

  def confirm
    @cart_items = current_customer.cart_items
    @order = Order.new(
    customer: current_customer,
    payment_method: params[:order][:payment_method]
    )

    if params[:order][:address_option] == "0"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name + current_customer.first_name

    elsif params[:order][:address_option] == "1"
      @ship = Address.find(params[:order][:address_id])
      @order.postal_code = @ship.postal_code
      @order.address = @ship.address
      @order.name = @ship.name

    elsif params[:order][:address_option] = "2"
      @order.postal_code = params[:order][:postal_code]
      @order.address = params[:order][:address]
      @order.name = params[:order][:name]

    end
  end

  def create
    @order = current_customer.orders.new(order_params)
    @order.save
    @cart_items = current_customer.cart_items
    if @order.total_payment != total_payment(@cart_items)
      current_customer.update(point: 0)
    end

    @cart_items.destroy_all
    redirect_to complete_orders_path
  end

  def index
    @orders = current_customer.orders
  end

  def show
    @order = Order.find(params[:id])
  end

  def complete
  end

  private
  def order_params
    params.require(:order).permit(:postal_code, :address, :name, :payment_method, :total_price)
  end

  def address_params
    params.require(:order).permit(:postal_code, :address, :name)
  end

  def check_cart_item
   unless current_customer.cart_items.present?
     redirect_to cart_items_path
   end
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  def tax_price(price)
    (price*1.1).floor
  end

  # 小計の計算
  def sub_price(sub)
    (tax_price(sub.item.price) * sub.amount)
  end

  # 合計金額の計算
  def total_price(totals)
    price = 0
    totals.each do |total|
      price += sub_price(total)
    end
    return price
  end

  # 請求合計金額の計算（注文履歴詳細画面）
  def billing_admin(order)
    total_price(order.order_details) + order.shoping_cost
  end
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md">
      <h3>注文履歴一覧</h3>
      <table class= "table">
        <tr>
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
        <% @orders.each do |order| %>
        <tr>
          <td>
            <%= link_to admin_order_path(order), class: "text-primary" do %>
              <%= l order.created_at %>
            <% end %>
          </td>
          <td><%= "#{order.customer.first_name}#{order.customer.last_name}" %></td>
          <td><%= order.order_details.count%></td>
          <td><%= order.order_status %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3 class= "mb-4">商品履歴詳細</h3>
      <table class=" table">
        <tr>
          <th>購入者</th>
          <td><%= "#{@order.customer.first_name}#{@order.customer.last_name}" %></td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= l @order.created_at %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td><%= @order.address %></td>
        </tr>
        <tr>
          <th>支払い方法</th>
          <td><%= @order.payment_method %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <div class="form-inline">
              <%= form_with model: @order, url: admin_order_path(@order), method: :patch do |f| %>
                <%= f.select :order_status, Order.order_statuses.keys,{},{class: "form-control form-control-sm mr-2"} %>
                <%= f.submit :"更新", class: "btn btn-success btn-sm"%>
              <% end %>
            </div>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <table class= "table">
        <tr>
          <th>商品名</th>
          <th>単価(税込)</th>
          <th>数量</th>
          <th>小計</th>
          <th>制作ステータス</th>
        </tr>
        <% @order.order_details.each do |order_detail| %>
        <tr>
          <td><%= order_detail.item.name %></td>
          <td><%= order_detail.item.price %></td>
          <td><%= order_detail.amount %></td>
          <td><%= sub_price(order_detail).to_s(:delimited) %></td>
          <td>
            <div class="form-inline">
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %>
                <%= f.select :production_status, OrderDetail.production_statuses.keys,{},{class: "form-control form-control-sm mr-2"} %>
                <%= f.submit :"更新", class: "btn btn-success btn-sm"%>
              <% end %>
            </div>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
    <div class="col-md-4 d-flex align-items-end">
      <table class="table">
        <tr>
          <th>商品合計</th>
          <td><%= total_price(@order.order_details).to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.postage %>円</td>
        </tr>
        <tr>
          <th>請求合計金額</th>
          <td><%= billing_admin(@order).to_s(:delimited) %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>